version: 2
jobs:
  convert-base-decision-for-university-practice:
    docker:
    - image: circleci/python:latest
    steps:
    - checkout
    - run:
        command: |
          if true; then
            pip install --user -r requirements.txt
          else
            pip install -r requirements.txt
          fi
        name: Install Dependencies
    - run:
        name: Jupyter get HTML
        command: |
          jupyter nbconvert —execute —to html base-decision-for-university-practice.ipynb
    - store_artifacts:
        path: ./base-decision-for-university-practice.html
workflows:
  main:
    jobs:
    - convert-base-decision-for-university-practice
  version: 2